name: ByteBans
version: '1.0.0'
main: io.github.lianjordaan.byteBans.ByteBans
api-version: '1.21'
authors: [ LianJordaan ]
commands:
  mute:
    description: Mutes a player
    usage: /mute <player> [<reason>] [<scope>]
    permission: bytebans.mute
  tempmute:
    description: Temporarily mutes a player
    usage: /tempmute <player> <time> [<reason>] [<scope>]
    permission: bytebans.tempmute
  unmute:
    description: Unmutes a player
    usage: /unmute <player> [<reason>]
    permission: bytebans.unmute
  ban:
    description: Bans a player
    usage: /ban <player> [<reason>] [<scope>]
    permission: bytebans.ban
  tempban:
    description: Temporarily bans a player
    usage: /tempban <player> <time> [<reason>] [<scope>]
    permission: bytebans.tempban
  unban:
    description: Unbans a player
    usage: /unban <player> [<reason>]
    permission: bytebans.unban
  kick:
    description: Kicks a player
    usage: /kick <player> [<reason>]
    permission: bytebans.kick
  removepunishment:
    description: Removes a punishment
    usage: /removepunishment <punishment ID>
    permission: bytebans.removepunishment
  refreshpunishments:
    description: Refreshes the punishments
    usage: /refreshpunishments
    permission: bytebans.refreshpunishments
permissions:
  bytebans.notify.silent:
    description: Allows the player to see silent punishments
    default: op
  bytebans.notify.speak_muted:
    description: Makes the player get a message when someone that is muted tries to speak
    default: op