name: ByteBans
version: '1.0'
main: io.github.lianjordaan.byteBans.ByteBans
api-version: '1.21'
authors: [ LianJordaan ]
commands:
  mute:
    description: Mutes a player
    usage: /mute <player> [<reason>] [<scope>]
    permission: bytebans.mute
  unmute:
    description: Unmutes a player
    usage: /unmute <player> [<reason>]
    permission: bytebans.unmute
  tempmute:
    description: Temporarily mutes a player
    usage: /tempmute <player> <time> [<reason>] [<scope>]
    permission: bytebans.tempmute
  ban:
    description: Bans a player
    usage: /ban <player> [<reason>] [<scope>]
    permission: bytebans.ban
  tempban:
    description: Temporarily bans a player
    usage: /tempban <player> <time> [<reason>] [<scope>]
    permission: bytebans.tempban
  unban:
    description: Unbans a player
    usage: /unban <player> [<reason>]
    permission: bytebans.unban
  banip:
    description: Bans an IP address
    usage: /banip <ip address> [<reason>] [<scope>]
    permission: bytebans.banip
  unbanip:
    description: Unbans an IP address
    usage: /unbanip <ip address> [<reason>]
    permission: bytebans.unbanip
  tempbanip:
    description: Temporarily bans an IP address
    usage: /tempbanip <ip address> <time> [<reason>] [<scope>]
    permission: bytebans.tempbanip
  kick:
    description: Kicks a player
    usage: /kick <player> [<reason>]
    permission: bytebans.kick
  removepunishment:
    description: Removes a punishment
    usage: /removepunishment <punishment ID>
    permission: bytebans.removepunishment